[2021-09-27 16:04:29,049] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-27T15:50:00+00:00 [queued]>
[2021-09-27 16:04:29,090] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-27T15:50:00+00:00 [queued]>
[2021-09-27 16:04:29,091] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 16:04:29,092] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-09-27 16:04:29,093] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-27 16:04:29,122] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): say_hello> on 2021-09-27T15:50:00+00:00
[2021-09-27 16:04:29,137] {standard_task_runner.py:52} INFO - Started process 24127 to run task
[2021-09-27 16:04:29,157] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'say_hello', '2021-09-27T15:50:00+00:00', '--job-id', '77', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpp6lo_pfc', '--error-file', '/tmp/tmpd7q6ixjx']
[2021-09-27 16:04:29,189] {standard_task_runner.py:77} INFO - Job 77: Subtask say_hello
[2021-09-27 16:04:29,292] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.say_hello 2021-09-27T15:50:00+00:00 [running]> on host 7c1d2d2abdb5
[2021-09-27 16:04:29,437] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Veerawat
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=say_hello
AIRFLOW_CTX_EXECUTION_DATE=2021-09-27T15:50:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-27T15:50:00+00:00
[2021-09-27 16:04:29,439] {my_dag.py:11} INFO - Hello, SAKSIAM
[2021-09-27 16:04:29,440] {python.py:151} INFO - Done. Returned value was: None
[2021-09-27 16:04:29,461] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=say_hello, execution_date=20210927T155000, start_date=20210927T160429, end_date=20210927T160429
[2021-09-27 16:04:29,510] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-27 16:04:29,579] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
