[2021-09-28 00:48:43,984] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-27T21:40:00+00:00 [queued]>
[2021-09-28 00:48:44,184] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-27T21:40:00+00:00 [queued]>
[2021-09-28 00:48:44,189] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-28 00:48:44,197] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-09-28 00:48:44,202] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-28 00:48:44,291] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): say_hello> on 2021-09-27T21:40:00+00:00
[2021-09-28 00:48:44,333] {standard_task_runner.py:52} INFO - Started process 25484 to run task
[2021-09-28 00:48:44,414] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'say_hello', '2021-09-27T21:40:00+00:00', '--job-id', '100', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpu0_v3ja6', '--error-file', '/tmp/tmpmbivhkky']
[2021-09-28 00:48:44,452] {standard_task_runner.py:77} INFO - Job 100: Subtask say_hello
[2021-09-28 00:48:44,891] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.say_hello 2021-09-27T21:40:00+00:00 [running]> on host 7c1d2d2abdb5
[2021-09-28 00:48:45,439] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Veerawat
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=say_hello
AIRFLOW_CTX_EXECUTION_DATE=2021-09-27T21:40:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-27T21:40:00+00:00
[2021-09-28 00:48:45,449] {my_dag.py:11} INFO - Hello, SAKSIAM
[2021-09-28 00:48:45,456] {python.py:151} INFO - Done. Returned value was: None
[2021-09-28 00:48:45,513] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=say_hello, execution_date=20210927T214000, start_date=20210928T004844, end_date=20210928T004845
[2021-09-28 00:48:45,741] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-28 00:48:45,849] {local_task_job.py:261} INFO - 0 downstream tasks scheduled from follow-on schedule check
