[2021-09-28 02:20:37,722] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-28T02:10:00+00:00 [queued]>
[2021-09-28 02:20:37,809] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: my_dag.say_hello 2021-09-28T02:10:00+00:00 [queued]>
[2021-09-28 02:20:37,811] {taskinstance.py:1095} INFO - 
--------------------------------------------------------------------------------
[2021-09-28 02:20:37,812] {taskinstance.py:1096} INFO - Starting attempt 1 of 1
[2021-09-28 02:20:37,815] {taskinstance.py:1097} INFO - 
--------------------------------------------------------------------------------
[2021-09-28 02:20:37,848] {taskinstance.py:1115} INFO - Executing <Task(PythonOperator): say_hello> on 2021-09-28T02:10:00+00:00
[2021-09-28 02:20:37,872] {standard_task_runner.py:52} INFO - Started process 25938 to run task
[2021-09-28 02:20:37,889] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'say_hello', '2021-09-28T02:10:00+00:00', '--job-id', '115', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp0mzab17c', '--error-file', '/tmp/tmpsmwh1i23']
[2021-09-28 02:20:37,897] {standard_task_runner.py:77} INFO - Job 115: Subtask say_hello
[2021-09-28 02:20:38,225] {logging_mixin.py:109} INFO - Running <TaskInstance: my_dag.say_hello 2021-09-28T02:10:00+00:00 [running]> on host 7c1d2d2abdb5
[2021-09-28 02:20:38,538] {taskinstance.py:1254} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Veerawat
AIRFLOW_CTX_DAG_ID=my_dag
AIRFLOW_CTX_TASK_ID=say_hello
AIRFLOW_CTX_EXECUTION_DATE=2021-09-28T02:10:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-28T02:10:00+00:00
[2021-09-28 02:20:38,541] {my_dag.py:11} INFO - Hello, SAKSIAM
[2021-09-28 02:20:38,542] {python.py:151} INFO - Done. Returned value was: None
[2021-09-28 02:20:38,629] {taskinstance.py:1219} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=say_hello, execution_date=20210928T021000, start_date=20210928T022037, end_date=20210928T022038
[2021-09-28 02:20:38,726] {local_task_job.py:151} INFO - Task exited with return code 0
[2021-09-28 02:20:38,823] {local_task_job.py:261} INFO - 1 downstream tasks scheduled from follow-on schedule check
